version: '3.2'

networks:
  app-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 192.167.150.0/24

services:

  # PostgreSQL Database Service
  db-pddikti:
    image: postgres:12
    command: ["postgres", "-c", "port=54333"]
    tty: true
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${APP_PATH_HOST}/pgsql/data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - db-pddikti
    deploy:
      restart_policy:
        condition: any

  # Application Service
  app-pddikti:
    image: ${APP_IMAGE:-neofeeder:latest}
    ports:
      - "${APP_PORT:-8100}:8100"
      - "${WS_PORT:-3003}:3003"
    tty: true
    environment:
      TZ: "Asia/Jakarta"
      SERVICE_NAME: "app"
      SERVICE_TAGS: "1.0.5"
      PGHOST: "db-pddikti"
      PGPORT: "54333"
    volumes:
      - ${APP_PATH_HOST}/prefill_pddikti:/prefill_pddikti
      - ${APP_PATH_HOST}/logs/supervisor:/var/log/supervisor
    networks:
      - app-network
    depends_on:
      - db-pddikti
    deploy:
      restart_policy:
        condition: any
